# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c2c5535a26fcdd1d93a93e91ffbcffdd33d897d5ac4fcc5c0260bb9bcf643d97300f26674bfff6fedd1e977a4369c893a80cde5bd62b46ca7ee94f76b951312

test:
  secret_key_base: f3b5394c45a875d69004305dcddfc9a3ac8b302a154d629f07fbaf52d643bed939c7cfbcedb0ceec12bc012ae3442a80fbaf3ac23de9596a400e19a023de437b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
